CREATE TABLE picture_bot.bot_user
(
    id                  BIGINT                      NOT NULL,
    first_seen          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_seen           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    settings_id         BIGINT,
    settings_message_id INTEGER,
    CONSTRAINT pk_bot_user PRIMARY KEY (id)
);

CREATE TABLE picture_bot.bot_user_details
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_name     VARCHAR(32),
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255),
    is_bot        BOOLEAN                                 NOT NULL,
    language_code VARCHAR(2)                              NOT NULL,
    user_id       BIGINT,
    CONSTRAINT pk_bot_user_details PRIMARY KEY (id)
);

CREATE TABLE picture_bot.daily_picture
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path      VARCHAR(255)                            NOT NULL,
    date_used date                                    NOT NULL,
    CONSTRAINT pk_daily_picture PRIMARY KEY (id)
);

CREATE TABLE picture_bot.event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_month  INTEGER                                 NOT NULL,
    month_of_year INTEGER                                 NOT NULL,
    path          VARCHAR(255)                            NOT NULL,
    greeting      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE picture_bot.settings
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_enabled         BOOLEAN                                 NOT NULL,
    schedule           time WITHOUT TIME ZONE                  NOT NULL,
    is_spoiler_enabled BOOLEAN                                 NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    last_modified      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    timezone_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_settings PRIMARY KEY (id)
);

CREATE TABLE picture_bot.timezone
(
    id   BIGINT       NOT NULL,
    city VARCHAR(100) NOT NULL,
    CONSTRAINT pk_timezone PRIMARY KEY (id)
);

ALTER TABLE picture_bot.bot_user
    ADD CONSTRAINT uc_bot_user_settings UNIQUE (settings_id);

ALTER TABLE picture_bot.event
    ADD CONSTRAINT uc_d7124acc8386d407a2f6ae80a UNIQUE (day_of_month, month_of_year);

ALTER TABLE picture_bot.settings
    ADD CONSTRAINT uc_settings_user UNIQUE (user_id);

ALTER TABLE picture_bot.bot_user_details
    ADD CONSTRAINT FK_BOT_USER_DETAILS_ON_USER FOREIGN KEY (user_id) REFERENCES picture_bot.bot_user (id);

ALTER TABLE picture_bot.bot_user
    ADD CONSTRAINT FK_BOT_USER_ON_SETTINGS FOREIGN KEY (settings_id) REFERENCES picture_bot.settings (id);

ALTER TABLE picture_bot.settings
    ADD CONSTRAINT FK_SETTINGS_ON_TIMEZONE FOREIGN KEY (timezone_id) REFERENCES picture_bot.timezone (id);

ALTER TABLE picture_bot.settings
    ADD CONSTRAINT FK_SETTINGS_ON_USER FOREIGN KEY (user_id) REFERENCES picture_bot.bot_user (id);
